imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Stof DoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\MainBundle\Entity\User
    registration:
        form:
            type: FOS\UserBundle\Form\Type\RegistrationFormType
            name: fos_user_registration_form
            validation_groups: [Registration, Core]
        confirmation:
            enabled: true
            template: '@FOSUserBundle:Registration:email.txt.twig'
    profile:
        form:
            type: FOS\UserBundle\Form\Type\ProfileFormType
    resetting:
        email:
            template: '@FOSUserBundle:Resetting:email.txt.twig'
    group:
        group_class: App\MainBundle\Entity\Group
    from_email:
        address: blog@domain.be
        sender_name: user

# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller: false
    bundles: [AppFrontBundle]
    filters:
        cssrewrite: ~
    assets:
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/dist/css/bootstrap.css'
            outputs: "css/bootstrap_css"
            filters: [cssrewrite]

        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/dist/js/bootstrap.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/alert.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/button.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/carousel.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/collapse.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/dropdown.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/modal.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/popover.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/scrollspy.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/tab.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/tooltip.js'
                - '%kernel.root_dir%/../web/assets/vendor/bootstrap/js/transition.js'
            outputs: "js/bootstrap_js"

        jquery:
            inputs:
                - '%kernel.root_dir%/../web/assets/vendor/jquery/dist/jquery.js'
            outputs: "js/jquery"

        fonts_glyphicons_eot:
            inputs:
                - "%kernel.root_dir%/../web/assets/vendor/bootstrap/fonts/glyphicons-halflings-regular.eot"
            outputs: "fonts/glyphicons-halflings-regular.eot"

        fonts_glyphicons_svg:
            inputs:
                 - "%kernel.root_dir%/../web/assets/vendor/bootstrap/fonts/glyphicons-halflings-regular.svg"
            outputs: "fonts/glyphicons-halflings-regular.svg"

        fonts_glyphicons_ttf:
            inputs:
                - "%kernel.root_dir%/../web/assets/vendor/bootstrap/fonts/glyphicons-halflings-regular.ttf"
            outputs: "fonts/glyphicons-halflings-regular.ttf"

        fonts_glyphicons_woff:
            inputs:
                 - "%kernel.root_dir%/../web/assets/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff"
            outputs: "fonts/glyphicons-halflings-regular.woff"

# VichUploader Bundle Configuration
#vich_uploader:
#    db_driver: orm
#    mappings:
#        post_image:
#            uri_prefix:         /post/images
#            upload_destination: "%kernel.root_dir%/../web/post/images"
#            namer: vich_uploader.namer_uniqid