app_front_homepage:
    path:     /
    defaults: { _controller: AppFrontBundle:Core:index }

app_front_news:
    path:     /news
    defaults: { _controller: AppFrontBundle:Core:news }

app_front_candidates:
    path:     /candidates
    defaults: { _controller: AppFrontBundle:Core:candidates }